//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        int HelloWorld(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<int> HelloWorldAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        int HelloWorld2(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld2", ReplyAction="*")]
        System.Threading.Tasks.Task<int> HelloWorld2Async(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld3", ReplyAction="*")]
        int HelloWorld3(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld3", ReplyAction="*")]
        System.Threading.Tasks.Task<int> HelloWorld3Async(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld4", ReplyAction="*")]
        int HelloWorld4(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld4", ReplyAction="*")]
        System.Threading.Tasks.Task<int> HelloWorld4Async(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApplication1.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.WebServiceSoap>, WindowsFormsApplication1.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int HelloWorld(int a, int b) {
            return base.Channel.HelloWorld(a, b);
        }
        
        public System.Threading.Tasks.Task<int> HelloWorldAsync(int a, int b) {
            return base.Channel.HelloWorldAsync(a, b);
        }
        
        public int HelloWorld2(int a, int b) {
            return base.Channel.HelloWorld2(a, b);
        }
        
        public System.Threading.Tasks.Task<int> HelloWorld2Async(int a, int b) {
            return base.Channel.HelloWorld2Async(a, b);
        }
        
        public int HelloWorld3(int a, int b) {
            return base.Channel.HelloWorld3(a, b);
        }
        
        public System.Threading.Tasks.Task<int> HelloWorld3Async(int a, int b) {
            return base.Channel.HelloWorld3Async(a, b);
        }
        
        public int HelloWorld4(int a, int b) {
            return base.Channel.HelloWorld4(a, b);
        }
        
        public System.Threading.Tasks.Task<int> HelloWorld4Async(int a, int b) {
            return base.Channel.HelloWorld4Async(a, b);
        }
    }
}
